### ISSUE TITLE
User Clarity of Terminology 

### ISSUE THREAD

**Issue by MrXarous** [emipa606/MachineGunDefence#1]
User Jello (Jello#4311) stated they couldn't build a m2 machine gun. Upon them setting up a testing environment with just Core/DLC and this mod was able to figure out it was user error due to clarity of wording/terminology. 

User recommended modifying the terminology to change the "Make .50Cal machine gun crate" to "Make m2 Machine Gun Crate" for better clarity.

**Comment by emipa606** [comment]
Good idea, should be fixed in ac1e01a
